import { ReminderList } from "./mock-reminder";
import { Patient } from "./patient";

export const PatientList: Patient[] = [
    {
        id:1,
        patient_name:"patient1",
        email:"patient1@gmail.com",
        password:"patient1",
        reminder:ReminderList[0],
        doctor_name:'doctor1',
        unfinished_high:3,
        unfinished_middle:3,
        unfinished_low:3
    },
    {
        id:2,
        patient_name:"patient2",
        email:"patient2@gmail.com",
        password:"patient2",
        reminder:ReminderList[1],
        doctor_name:'doctor3',
        unfinished_high:3,
        unfinished_middle:3,
        unfinished_low:3
    },
    {
        id:3,
        patient_name:"patient3",
        email:"patient3@gmail.com",
        password:"patient3",
        reminder:ReminderList[0],
        doctor_name:'doctor3',
        unfinished_high:2,
        unfinished_middle:1,
        unfinished_low:0
    },
    {
        id:4,
        patient_name:"patient4",
        email:"patient4@gmail.com",
        password:"patient4",
        reminder:ReminderList[2],
        doctor_name:'doctor4',
        unfinished_high:0,
        unfinished_middle:0,
        unfinished_low:1
    },
    {
        id:5,
        patient_name:"patient5",
        email:"patient5@gmail.com",
        password:"patient5",
        reminder:ReminderList[1],
        doctor_name:'doctor5',
        unfinished_high:1,
        unfinished_middle:1,
        unfinished_low:2
    },
    {
        id:6,
        patient_name:"patient6",
        email:"patient6@gmail.com",
        password:"patient6",
        reminder:ReminderList[0],
        doctor_name:'doctor6',
        unfinished_high:0,
        unfinished_middle:2,
        unfinished_low:1
    },
    {
        id:7,
        patient_name:"patient7",
        email:"patient7@gmail.com",
        password:"patient7",
        reminder:ReminderList[1],
        doctor_name:'doctor7',
        unfinished_high:0,
        unfinished_middle:0,
        unfinished_low:0
    },
    {
        id:8,
        patient_name:"patient8",
        email:"patient8@gmail.com",
        password:"patient8",
        reminder:ReminderList[0],
        doctor_name:'doctor8',
        unfinished_high:0,
        unfinished_middle:0,
        unfinished_low:2
    },
    {
        id:9,
        patient_name:"patient9",
        email:"patient9@gmail.com",
        password:"patient9",
        reminder:ReminderList[0],
        doctor_name:'doctor9',
        unfinished_high:1,
        unfinished_middle:2,
        unfinished_low:2
    },
    {
        id:10,
        patient_name:"patient10",
        email:"patient10@gmail.com",
        password:"patient10",
        reminder:ReminderList[1],
        doctor_name:'doctor10',
        unfinished_high:3,
        unfinished_middle:3,
        unfinished_low:3
    },
    {
        id:11,
        patient_name:"patient11",
        email:"patient11@gmail.com",
        password:"patient11",
        reminder:ReminderList[0],
        doctor_name:'doctor11',
        unfinished_high:3,
        unfinished_middle:3,
        unfinished_low:3
    },
]